name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Archive application
        run: |
          zip -r application.zip .

      - name: Upload to AWS S3
        run: |
          aws s3 cp application.zip s3://a-big-red-bucket/application.zip

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment --application-name A-Big-Red-CodeDeploy --deployment-group-name A-Big-Red-Deployment-Group --s3-location bucket=a-big-red-bucket,key=application.zip,bundleType=zip

  deploy-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js using NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
          nvm install 18
      - name: Clone repository
        run: git clone https://github.com/mike-rv/big-red-acebook.git
      - name: Change directory
        run: cd big-red-acebook && pwd
      - name: Install Node.js dependencies
        run: npm install
      - name: Install MongoDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb
      - name: Run ESLint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Start the server
        run: npm start


