name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Archive application
        run: |
          zip -r application.zip .

      - name: Upload to AWS S3
        run: |
          aws s3 cp application.zip s3://a-big-red-bucket/application.zip

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment --application-name A-Big-Red-CodeDeploy --deployment-group-name A-Big-Red-Deployment-Group --s3-location bucket=a-big-red-bucket,key=application.zip,bundleType=zip

  deploy-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        run: |
          brew install nvm
          source ~/.bash_profile
          nvm install 18
      - name: Clone repository
        run: git clone https://github.com/mike-rv/big-red-acebook.git
      - name: Change directory
        run: cd big-red-acebook
      - name: Install Node.js dependencies
        run: npm install
      - name: Install MongoDB
        run: |
          brew tap mongodb/brew
          brew install mongodb-community@5.0
          brew services start mongodb-community@5.0
      - name: Run ESLint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Start the server
        run: npm start








